spring:
  profiles:
    active: pro


# 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf8&useSSL=false
#    useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# jpa配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

# 对于thymeleaf模板进行配置
# qq:spring.mail.host=smtp.qq.com spring.mail.password=QQ邮箱授权码
# mail 配置
  mail:
    host: smtp.163.com
    username: 17761276235@163.com
    password: Qiao19930726
    properties: true
    default-encoding: utf-8
    port: 25
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
    #    suffix: .html
    #    mode: HTML5
    #    encoding: UTF-8
    #    content-type: text/html
    #    注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改
# Mybatis 配置
mybatis:
  type-aliases-package: com.imooc.demo.entity
  mapper-locations: clathpath:mapper/*.xml







