spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf8&useSSL=false
#    useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp.163.com
    username: 17761276235@163.com
    password: Qiao19930726
    properties: true
    default-encoding: utf-8
    port: 25


# qq:spring.mail.host=smtp.qq.com spring.mail.password=QQ邮箱授权码